title: Homepage
author: Jonathan Retzack
email: retzackj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  College student. Coder. Coffee drinker. Ready to contribute and learn more.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
